# Generated by Django 5.2.17 on 2026-08-25 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKPIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('report_date', models.DateField(unique=True)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('units_received', models.PositiveIntegerField(default=0)),
                ('repairs_completed', models.PositiveIntegerField(default=0)),
                ('rma_opened', models.PositiveIntegerField(default=0)),
                ('total_stock_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
