# Generated by Django 5.2.17 on 2026-08-25 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('support_phone', models.CharField(blank=True, max_length=32)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisplaySpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('size_inches', models.DecimalField(decimal_places=1, help_text='e.g. 13.3, 14.0, 15.6, 16.0, 17.3', max_digits=4)),
                ('resolution', models.CharField(help_text='e.g. 1920x1080 (FHD), 2560x1440 (QHD), 3840x2160 (4K)', max_length=64)),
                ('panel_type', models.CharField(choices=[('IPS', 'IPS LCD'), ('OLED', 'OLED'), ('VA', 'VA'), ('TN', 'TN LCD')], default='IPS', max_length=32)),
                ('refresh_rate_hz', models.PositiveSmallIntegerField(default=60)),
                ('is_touchscreen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GpuSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('brand', models.CharField(choices=[('NVIDIA', 'NVIDIA GeForce / RTX'), ('AMD', 'AMD Radeon'), ('INTEL', 'Intel Arc / Iris Xe'), ('APPLE', 'Apple GPU')], max_length=64)),
                ('model_name', models.CharField(max_length=128)),
                ('vram_gb', models.PositiveSmallIntegerField(default=0, help_text='0 for Integrated Graphics')),
                ('is_dedicated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaptopCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Laptop Categories',
            },
        ),
        migrations.CreateModel(
            name='ProcessorSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('brand', models.CharField(choices=[('INTEL', 'Intel'), ('AMD', 'AMD'), ('APPLE', 'Apple Silicon'), ('QUALCOMM', 'Qualcomm Snapdragon')], max_length=64)),
                ('model_name', models.CharField(help_text='e.g. Core i7-13700H, Ryzen 7 7840U, M3 Pro', max_length=128)),
                ('generation', models.CharField(blank=True, max_length=64)),
                ('cores', models.PositiveSmallIntegerField(default=4)),
                ('threads', models.PositiveSmallIntegerField(default=8)),
                ('base_clock_ghz', models.DecimalField(decimal_places=2, default=2.4, max_digits=4)),
                ('boost_clock_ghz', models.DecimalField(decimal_places=2, default=4.8, max_digits=4)),
                ('cache_mb', models.PositiveSmallIntegerField(default=12)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RamSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('ram_type', models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5'), ('LPDDR4X', 'LPDDR4X'), ('LPDDR5', 'LPDDR5'), ('UNIFIED', 'Apple Unified Memory')], max_length=32)),
                ('capacity_gb', models.PositiveIntegerField(help_text='Capacity in Gigabytes (e.g. 8, 16, 32, 64)')),
                ('speed_mhz', models.PositiveIntegerField(default=3200)),
                ('is_expandable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('storage_type', models.CharField(choices=[('NVME_SSD', 'M.2 NVMe PCIe SSD'), ('SATA_SSD', '2.5" SATA SSD'), ('HDD', 'Mechanical HDD'), ('EMMC', 'eMMC Embedded')], max_length=32)),
                ('capacity_gb', models.PositiveIntegerField(help_text='Capacity in GB (e.g. 256, 512, 1024, 2048)')),
                ('form_factor', models.CharField(default='M.2 2280', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('component_type', models.CharField(choices=[('RAM', 'Memory Module (RAM)'), ('STORAGE', 'Storage Drive (SSD/HDD)'), ('SCREEN', 'Display Panel'), ('BATTERY', 'Laptop Battery'), ('KEYBOARD', 'Keyboard Assembly'), ('MOTHERBOARD', 'System Board / Motherboard'), ('CHARGER', 'AC Power Adapter'), ('FAN', 'Cooling Fan / Heatsink')], max_length=32)),
                ('part_number', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('specification_summary', models.TextField(blank=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.brand')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('model_name', models.CharField(help_text='e.g. ThinkPad T14 Gen 4, Latitude 7420, MacBook Pro 14', max_length=255)),
                ('model_number', models.CharField(help_text='Manufacturer part/model SKU', max_length=128, unique=True)),
                ('operating_system', models.CharField(default='Windows 11 Pro', max_length=64)),
                ('msrp_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_stock_threshold', models.PositiveIntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='laptops/')),
                ('description', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='inventory.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laptops', to='inventory.laptopcategory')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.displayspec')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.gpuspec')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.processorspec')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.ramspec')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.storagespec')),
            ],
            options={
                'ordering': ['brand', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='LaptopUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('serial_number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=128, unique=True)),
                ('imei_or_asset_tag', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('INWARD_RECEIVED', 'Inward Received (Pending QC)'), ('IN_QC', 'Under Inward Quality Check'), ('QC_FAILED', 'Failed QC Inspection'), ('IN_STOCK', 'Available in Stock'), ('RESERVED', 'Reserved for Sales Order'), ('IN_WORKSHOP', 'In Repair / Refurbishing Workshop'), ('DIAGNOSTICS_COMPLETED', 'Diagnostics Completed'), ('READY_FOR_DISPATCH', 'Ready for Dispatch'), ('SHIPPED', 'Shipped to Customer'), ('RMA_RETURNED', 'Returned via RMA'), ('SCRAPPED', 'Scrapped / Salvaged for Parts')], db_index=True, default='INWARD_RECEIVED', max_length=32)),
                ('condition_grade', models.CharField(choices=[('NEW', 'Brand New (Sealed)'), ('OPEN_BOX', 'Open Box (Like New)'), ('GRADE_A_PLUS', 'Grade A+ (Flawless Refurbished)'), ('GRADE_A', 'Grade A (Minor cosmetic signs)'), ('GRADE_B', 'Grade B (Noticeable cosmetic scratches)'), ('GRADE_C', 'Grade C (Dents / Heavy wear)'), ('SCRAP', 'Grade Scrap (Non-functional)')], default='GRADE_A', max_length=32)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('battery_health_percentage', models.PositiveSmallIntegerField(default=100)),
                ('battery_cycle_count', models.PositiveIntegerField(default=0)),
                ('current_location', models.CharField(default='Inward Dock', help_text='Warehouse Bin or Department location', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('laptop_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.laptopmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SerialLifecycleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('reference_document', models.CharField(blank=True, help_text='PO #, Job Card #, Invoice #, or RMA #', max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='inventory.laptopunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('is_oem', models.BooleanField(default=True, help_text='Original Equipment Manufacturer component')),
                ('installation_notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_models', to='inventory.componentitem')),
                ('laptop_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='inventory.laptopmodel')),
            ],
            options={
                'unique_together': {('laptop_model', 'component')},
            },
        ),
    ]
