# Generated by Django 5.2.17 on 2026-08-25 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(max_length=128)),
                ('duration_months', models.PositiveSmallIntegerField(default=12)),
                ('terms_and_conditions', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RMATicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('rma_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'RMA Request Submitted'), ('APPROVED', 'RMA Approved - Awaiting Return'), ('RECEIVED', 'Unit Received at RMA Hub'), ('INSPECTION', 'Under RMA Inspection'), ('REPLACEMENT_DISPATCHED', 'Replacement Dispatched'), ('CREDIT_ISSUED', 'Credit Note Issued'), ('REJECTED', 'RMA Rejected (Out of Warranty / Abuse)'), ('CLOSED', 'RMA Closed')], default='SUBMITTED', max_length=32)),
                ('reason_for_return', models.TextField()),
                ('inspection_notes', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_claims', to='sales.customer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_tickets', to='inventory.laptopunit')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductWarrantyRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='sales.customer')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_record', to='inventory.laptopunit')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warranty.warrantypolicy')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
